-- ═══════════════════════════════════════════════════════════════
-- Migration: v9_8_1
-- Purpose: Fix session_log.session_id to allow manual inserts from
--          frontend identity.ts (ensureSessionPersisted).
-- Root:    GENERATED ALWAYS blocks INSERT of session_id value.
-- Fix:     GENERATED BY DEFAULT allows manual INSERT to coexist
--          with auto-generation, maintaining PK integrity.
-- Date:    2026-05-22
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- Switch from GENERATED ALWAYS to GENERATED BY DEFAULT
-- The DROP + ADD pattern is safe for re-runs via IF EXISTS.
ALTER TABLE public.session_log 
  ALTER COLUMN session_id DROP IDENTITY IF EXISTS;

ALTER TABLE public.session_log 
  ALTER COLUMN session_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Bump APP_VERSION
UPDATE public.system_config 
SET config_value = 'v9.8.1', modified_at = NOW() 
WHERE config_name = 'APP_VERSION';

COMMIT;
