"""
Clinical Backdating — §3.3 Timestamp Sovereignty.
Verifies the vault_finalize_intake RPC payload does NOT allow the UI
to override intake_timestamp with a past date.  The DB enforces NOW().
"""
import pytest
from unittest.mock import MagicMock, patch
from streamlit.testing.v1 import AppTest


def test_ui_cannot_override_intake_timestamp():
    """
    §3.3: intake_timestamp is generated by the DB (TIMESTAMPTZ DEFAULT NOW()).
    The Python payload must NOT include a manually crafted past timestamp;
    the RPC call should succeed and the DB clock governs.
    This test confirms the UI payload does not inject a backdated value.
    """
    mock_sb = MagicMock()
    mock_sb.table.return_value.select.return_value.execute.return_value.data = [
        {"species_id": "SN", "species_code": "SN", "common_name": "Snapping Turtle", "intake_count": 1}
    ]
    mock_sb.rpc.return_value.execute.return_value.data = [
        {"intake_id": "I-BD-001", "first_bin_id": "SN1-BD-1"}
    ]

    with patch("utils.bootstrap.bootstrap_page", return_value=mock_sb), \
         patch("streamlit.switch_page"):
        at = AppTest.from_file("vault_views/2_New_Intake.py")
        at.session_state.observer_id = "bd-observer"
        at.session_state.session_id = "bd-session"
        at.run()

        at.text_input[0].set_value("2026-BD-001")
        at.text_input[1].set_value("Backdater")
        at.session_state.bin_rows[0]["mass"] = 100.0
        at.session_state.bin_rows[0]["temp"] = 28.0
        at.run()

        save_btn = next(b for b in at.button if b.label == "SAVE")
        save_btn.click().run()

        assert not at.exception, f"Uncaught exception: {at.exception}"
        assert mock_sb.rpc.called, "RPC was not called — cannot verify timestamp handling."

        rpc_args = mock_sb.rpc.call_args
        params = rpc_args[1].get("params", {}) if rpc_args[1] else {}
        payload = params.get("p_payload", {})

        # The UI must NOT inject a custom intake_timestamp — the DB governs this via DEFAULT NOW()
        # If it is present, it must be None / absent (not a manually crafted past date).
        injected_ts = payload.get("intake_timestamp")
        if injected_ts:
            import datetime
            try:
                parsed = datetime.datetime.fromisoformat(str(injected_ts).replace("Z", "+00:00"))
                # If a timestamp is provided, it must be recent (within the last 60 seconds)
                now = datetime.datetime.now(datetime.timezone.utc)
                delta = abs((now - parsed).total_seconds())
                assert delta < 60, (
                    f"UI injected a backdated intake_timestamp: {injected_ts}. "
                    f"Delta from now: {delta:.0f}s. Timestamp sovereignty violation."
                )
            except ValueError:
                pytest.fail(f"intake_timestamp is not a valid ISO datetime: {injected_ts}")
